# Generated by Django 4.1.5 on 2023-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_name_person_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
