# Generated by Django 4.1.5 on 2023-10-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_menu_menu_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
