# Generated by Django 4.1.5 on 2023-10-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
