# Generated by Django 4.1.5 on 2023-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_bookings_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
